framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    #http_method_override: true
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions'
#
#    router:
#        default_uri: '%env(string:HTTP_HOST)%'